version: '3'

networks:
  spring:
    driver: bridge


services:

  postgres-user:
    image: "postgres:16-alpine"
    container_name: postgres-user
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER_DATABASE}
    ports:
      - "5435:5432"
    networks:
      - spring

  postgres-order:
    image: "postgres:16-alpine"
    container_name: postgres-order
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_ORDER_DATABASE}
    ports:
      - "5433:5432"
    networks:
      - spring

  postgres-product:
    image: "postgres:16-alpine"
    container_name: postgres-product
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PRODUCT_DATABASE}
    ports:
      - "5434:5432"
    networks:
      - spring

  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms-notification
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - '27017:27017'
    networks:
      - spring
