version: '3'

networks:
  app-network:
    driver: bridge

services:
  postgres-db:
    image: "postgres:15.1-alpine"
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - app-network
