server:
  port: 8084
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ReviewService
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_REVIEW_HOST}
      port: ${MONGO_REVIEW_PORT}
      database: ${MONGO_REVIEW_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
